/*


 Copyright 2012 Paizo Publishing, LLC

*/
var PAIZO={POPUP:{}};PAIZO.POPUP.version="1.0.5d";PAIZO.POPUP.OBSERVABLE={};PAIZO.UTIL={};PAIZO.UTIL.postRoll=function(a,b){PAIZO.UTIL.addToPost("[dice="+b+"]"+a+"[/dice]\n")};PAIZO.UTIL.addToPost=function(a){var b=document.getElementById("postBody");b&&a&&(b.value+=a)};
PAIZO.UTIL.expandInlineBlock=function(a,b){var c=a;if(!(0>navigator.userAgent.indexOf("MSIE 8")))for(;c.parentNode;)c=c.parentNode,c.className&&0<=c.className.indexOf("bb-frame")&&0<=c.parentNode.className.indexOf("bb-float-")&&(c.style.display=b?"block":"inline-block")};PAIZO.UTIL.addEventListener=function(a,b,c){a&&c&&(a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c))};
PAIZO.UTIL.removeEventListener=function(a,b,c){a&&c&&(a.addEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c))};PAIZO.UTIL.getPosition=function(a){var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}return{x:b,y:c}};PAIZO.UTIL.isNamed=function(a,b){return a&&(a.id&&a.id===b||a.className&&0<=a.className.indexOf(b))?!0:!1};
PAIZO.UTIL.getNamedChild=function(a,b){var c=a,d;if(PAIZO.UTIL.isNamed(a,b))return a;if(a.childNodes&&0<a.childNodes.length)for(c=a.childNodes.length;c--;)if(d=a.childNodes[c],0<d.childNodes.length&&(d=PAIZO.UTIL.getNamedChild(d,b)))return d;return null};PAIZO.UTIL.getNamedParent=function(a,b){for(var c=a;c.parentNode;){if(PAIZO.UTIL.isNamed(c.parentNode,b))return c.parentNode;c=c.parentNode}return null};
PAIZO.UTIL.getNamedParentOrSelf=function(a,b){return PAIZO.UTIL.isNamed(a,b)?a:PAIZO.UTIL.getNamedParent(a,b)};PAIZO.UTIL.getNamedSibling=function(a,b){for(var c=a;c.nextSibling;){if(PAIZO.UTIL.isNamed(c.nextSibling,b))return c.nextSibling;c=c.nextSibling}for(;c.previousSibling;){if(PAIZO.UTIL.isNamed(c.previousSibling,b))return c.previousSibling;c=c.previousSibling}return null};
PAIZO.POPUP.getDisplay=function(a,b){var c=PAIZO.UTIL.getNamedSibling(a,b);c||(c=PAIZO.UTIL.getNamedParent(a,b));return c?{y:a.offsetHeight+a.offsetTop,parentElem:c}:null};PAIZO.POPUP.addRequestToDiv=function(a,b){b.parentElem.innerHTML=a.responseText;PAIZO.POPUP.removeOnUnlock&&(PAIZO.POPUP.remove(PAIZO.POPUP.removeOnUnlock,!0),PAIZO.POPUP.removeOnUnlock=!1);PAIZO.POPUP.lock=!1};
PAIZO.POPUP.resizeParent=function(a){var b=a.offsetParent.offsetHeight,c=PAIZO.UTIL.getNamedChild(a,"tab-panel"),c=(c?c.offsetHeight:a.offsetHeight)+a.offsetTop;c>b&&(a.offsetParent.style.height=c+"px")};PAIZO.POPUP.moveChild=function(a){var b=a.offsetParent.offsetParent.offsetHeight,c=PAIZO.UTIL.getNamedChild(a,"tab-panel");if((c?c.offsetHeight:a.offsetHeight)+a.offsetTop>b)c.style.bottom="4px"};
PAIZO.POPUP.moveChildWithinElement=function(a,b){var c=PAIZO.UTIL.getNamedChild(a,"tab-panel"),d=PAIZO.UTIL.getNamedChild(PAIZO.UTIL.getNamedChild(a,"tp-content"),"bb-content");if(c){b&&b.length&&(b=PAIZO.UTIL.getNamedParent(a,b));b||(b=document.getElementsByTagName("body")[0]);c.offsetWidth<d.offsetWidth&&(c.style.width=d.offsetWidth+10+"px");parentRect={x:0,y:0,width:b.offsetWidth,height:b.offsetHeight};parentOffset=PAIZO.UTIL.getPosition(b);moveOffset=PAIZO.UTIL.getPosition(PAIZO.UTIL.getNamedParent(c,
"ajax-modal-container"));moveOffset={x:0-(moveOffset.x-parentOffset.x),y:0-(moveOffset.y-parentOffset.y)};if(c.offsetWidth>parentRect.width)c.style.left=(parentRect.width-c.offsetWidth)/2+"px";else if(c.offsetWidth>parentRect.width+moveOffset.x&&(c.style.left=parentRect.width+moveOffset.x-c.offsetWidth+"px",d=PAIZO.UTIL.getNamedChild(c,"tp-front-tab")))d.style.left=0-(parentRect.width+moveOffset.x-c.offsetWidth)+"px";c.offsetHeight>parentRect.height?c.style.top=(parentRect.height-c.offsetHeight)/
2+"px":c.offsetHeight>parentRect.height+moveOffset.y&&(c.style.top=parentRect.height+moveOffset.y-c.offsetHeight+"px")}};
PAIZO.POPUP.adjustPopups=function(a){var b=PAIZO.UTIL.classElements("popup"),c;if(b)for(x=b.length;x--;)if((c=PAIZO.UTIL.getNamedParent(b[x],"ajax-modal-container"))&&(0>c.className.indexOf("amc-hide")||c.style.visibility&&"visible"===c.style.visibility))a?PAIZO.POPUP.resizeParent(b[x]):(c=PAIZO.UTIL.getNamedSibling(c,c.id+"Link"))&&!(0<=c.className.indexOf("popup-still"))&&(c.attributes["enclosure-id"]?PAIZO.POPUP.moveChildWithinElement(b[x],c.attributes["enclosure-id"].value):PAIZO.POPUP.moveChildWithinElement(b[x],
document.getElementsByTagName("standard-center")[0]))};PAIZO.UTIL.classElements=function(a,b){var c=[],d,e=0,f;if(document.getElementsByClassName)return document.getElementsByClassName(a);if(document.querySelectorAll)return document.querySelectorAll("."+a);if((f=document.getElementsByTagName(b||"div"))&&0<f.length){for(d=f.length;d--;)f[d].className&&0<=f[d].className.indexOf(a)&&(c[e++]=f.x);if(0!=e)return c}return null};
PAIZO.POPUP.createPopup=function(a,b,c){var d,e;PAIZO.POPUP.removeTarget=b.parentElem;if(0<=b.parentElem.className.indexOf("amc-hide")){b.parentElem.style.visibility="visible";PAIZO.UTIL.getNamedChild(b.parentElem,"popup").style.display="block";if(e=PAIZO.UTIL.getNamedParent(b.parentElem,"messageboard-box"))e.className+=" mbb-top-indexed";if(e=PAIZO.UTIL.getNamedParentOrSelf(b.parentElem,"list-message"))e.className+=" wa-open";c&&PAIZO.UTIL.addEventListener(document,"click",PAIZO.POPUP.onRemove);
PAIZO.POPUP.lock=!1;PAIZO.POPUP.adjustPopups(!1)}else if((d=PAIZO.POPUP.getRequest())&&a)d.onreadystatechange=function(){var e=PAIZO.POPUP.OBSERVABLE.ASB;4==d.readyState&&(200==d.status&&PAIZO.POPUP.removeTarget)&&(b.parentElem.updateURL=a,PAIZO.POPUP.addRequestToDiv(d,b),c&&PAIZO.UTIL.addEventListener(document,"click",PAIZO.POPUP.onRemove),PAIZO.POPUP.adjustPopups(!1),e&&ASB.observeDescendentFields(e.updateContainerID,e.containerID,e.observeFieldFrequency,e.partial,e.observeDelay,e.options))},d.open("GET",
a,!0),d.setRequestHeader("x-requested-with","XMLHttpRequest"),d.send()};PAIZO.POPUP.fromMouseClick=function(a,b){PAIZO.POPUP.fromMouseEvent(null,null,a,!0);window.event?window.event.cancelBubble=!0:b&&(b.stopImmediatePropogation&&b.stopImmediatePropogation(),b.stopPropagation());return!1};PAIZO.POPUP.fromMouseOver=function(a){a.onmouseout?PAIZO.POPUP.fromMouseEvent(null,null,a,!1):PAIZO.POPUP.fromMouseEvent(null,null,a,!0);return!0};
PAIZO.POPUP.fromMouseEvent=function(a,b,c,d){PAIZO.POPUP.lock||(PAIZO.POPUP.lock=!0,PAIZO.POPUP.removeTarget&&PAIZO.POPUP.remove(null,!0),(a=c?3==c.nodeType?c.parent:c:a?3==a.target.nodeType?a.target.parent:a.target:window.event.srcElement)?a.attributes.version&&a.attributes.version.value!=PAIZO.POPUP.version?(alert('Component using wrong version number: Component="'+a.attributes.version.value+'", jsVersion="'+PAIZO.POPUP.version+'"'),PAIZO.POPUP.lock=!1):(a.id&&/.+Link$/.test(a.id)&&(a.parentname=
a.id.substr(0,a.id.length-4)),c=a.parentname?a.parentname:"bb-content",c=PAIZO.POPUP.getDisplay(a,c),b=null!=b?b:a.href||a.attributes.href.value,null===b?PAIZO.POPUP.lock=!1:PAIZO.POPUP.createPopup(b,c,d)):PAIZO.POPUP.lock=!1)};
PAIZO.POPUP.remove=function(a,b){var c=a?a:window.event,d=c?c.relatedTarget||c.toElement:null;if(!d&&c&&(c.target||c.srcElement))d=c.target||c.srcElement;if(d&&(0>d.className.indexOf("always-close")&&null==PAIZO.UTIL.getNamedParentOrSelf(d,"always-close")&&null!=PAIZO.UTIL.getNamedParentOrSelf(d,"allow-internal-clicks")||(c=PAIZO.UTIL.getNamedParent(d,"ajax-simple-toggle"))&&PAIZO.POPUP.removeTarget&&PAIZO.POPUP.removeTarget.id+"Link"===c.id&&0>PAIZO.POPUP.removeTarget.className.indexOf("amc-hide")))return!0;
if(PAIZO.POPUP.removeTarget){if(!b&&PAIZO.POPUP.lock)return PAIZO.POPUP.removeOnUnlock=!0;if(c=PAIZO.UTIL.getNamedParent(PAIZO.POPUP.removeTarget,"messageboard-box"))c.className=c.className.replace(/\s*mbb-top-indexed/,"");if(c=PAIZO.UTIL.getNamedParent(PAIZO.POPUP.removeTarget,"list-message"))c.className=c.className.replace(/\s*wa-open/,"");if(0<=PAIZO.POPUP.removeTarget.className.indexOf("amc-hide"))PAIZO.POPUP.removeTarget.style.visibility="hidden";else{if(PAIZO.POPUP.removeTarget.updateURL&&(request=
PAIZO.POPUP.getRequest()))request.open("GET",PAIZO.POPUP.removeTarget.updateURL,!0),request.setRequestHeader("x-requested-with","XMLHttpRequest"),request.send();for(;PAIZO.POPUP.removeTarget.firstChild;)PAIZO.POPUP.removeTarget.removeChild(PAIZO.POPUP.removeTarget.firstChild)}PAIZO.POPUP.removeTarget=null;PAIZO.UTIL.removeEventListener(document,"click",PAIZO.POPUP.onRemove)}return!0};PAIZO.POPUP.getRequest=function(){return window.XMLHttpRequest?new window.XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP")};
PAIZO.POPUP.reregisterPopup=function(){var a=PAIZO.UTIL.classElements("popup-opened");if(a&&0<a.length&&(a=a[0],a.className=a.className.replace(/ popup-opened/,""),PAIZO.POPUP.removeTarget=PAIZO.POPUP.getDisplay(a,"ajax-modal-container").parentElem,(a=PAIZO.POPUP.getDisplay(PAIZO.POPUP.removeTarget,PAIZO.POPUP.removeTarget.id+"Link").parentElem)&&a.attributes.href))PAIZO.POPUP.removeTarget.updateURL=a.attributes.href.value;PAIZO.POPUP.adjustPopups(!1)};
PAIZO.POPUP.OBSERVABLE.setUpdate=function(){var a=document.getElementsByTagName("script"),b,c=/ASB.observeDescendentFields\(\s*'([^']*)',\s*'([^']*)'\s*,\s*([0-9\.]*|null)\s*,\s*(true|false|null)\s*,\s*([0-9\.]+|null)\s*,\s*({.*})\s*\);/i,d;if(a&&0<a.length)for(x=a.length;x--;)if(a[x].childNodes&&0<a[x].childNodes.length||a[x].innerHTML)if(b=a[x].innerHTML?a[x]:a[x].childNodes[0],script=b.innerHTML?b.innerHTML:b.nodeValue,c.test(script)){a=c.exec(script);"null"===a[6]?d=null:(d="null"===d?null:a[6].replace(/([a-zA-Z_]*):\t*([^'][^\t]*)\t*[,]?/g,
'"$1":$2').replace(/([a-zA-Z0-9_]*):'([^']*)'/g,'"$1":"$2"'),d=window.JSON?JSON.parse(d):json_parse(d));PAIZO.POPUP.OBSERVABLE.ASB={updateContainerID:a[1],containerID:a[2],observeFieldFrequency:"null"===a[3]?null:Number(a[3]),partial:"true"===a[4]?!0:!1,observeDelay:"null"===a[5]?null:Number(a[5]),options:d};break}};
PAIZO.POPUP.OBSERVABLE.setOnload=function(){document.addEventListener?document.addEventListener("DOMContentLoaded",PAIZO.POPUP.OBSERVABLE.setUpdate,!1):document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&PAIZO.POPUP.OBSERVABLE.setUpdate()})};PAIZO.POPUP.onRemove=function(a){var b=a?a:window.event;if(b&&(b=b.srcElement?b.srcElement:b.target)&&0<=b.className.indexOf("ajax-simple-toggle"))return!0;PAIZO.POPUP.remove(a,!1)};
PAIZO.POPUP.fromMouseOut=function(a){var b=a?a:window.event,a=b?b.relatedTarget||b.toElement:null,b=b?b.srcElement||b.target:null;if(a&&b&&(b=PAIZO.UTIL.getNamedParentOrSelf(b,"ajax-simple-toggle")||PAIZO.UTIL.getNamedParentOrSelf(b,"popup"),a=PAIZO.UTIL.getNamedParentOrSelf(a,"ajax-simple-toggle")||PAIZO.UTIL.getNamedParentOrSelf(a,"popup"),b&&a)){PAIZO.UTIL.isNamed(a,"popup")&&(a.onmouseout=PAIZO.POPUP.fromMouseOut);return}PAIZO.POPUP.remove()};this.expandInlineBlock||(expandInlineBlock=PAIZO.UTIL.expandInlineBlock);var requestObjects={},flagging=!1;function _sendRequest(a,b,c,d){var e;window.XMLHttpRequest?e=new XMLHttpRequest:window.ActiveXObject&&(isIE=!0,e=new ActiveXObject("Microsoft.XMLHTTP"));e&&(requestObjects[c]=e,e.onreadystatechange=d,e.open("POST",a,!0),e.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),e.setRequestHeader("charset","UTF-8"),a=b+"&wosid="+encodeURIComponent(sessionID)+"&woinst="+encodeURIComponent(instanceNumber)+"&x="+encodeURIComponent(sessionID),e.send(a))}
function _removeChildNodes(a){for(;a.firstChild;)a.removeChild(a.firstChild)}function favoritePost(a){var b=document.getElementById("faq"+a);b.style.visibility="inherit";b.innerHTML="Adding favorite...";_sendRequest("/cgi-bin/WebObjects/"+applicationName+".woa/wa/DirectAction/favoritePost","post="+encodeURIComponent(a),"favorite",processfavorite)}
function unfavoritePost(a){var b=document.getElementById("faq"+a);b.style.visibility="inherit";b.innerHTML="Removing favorite...";_sendRequest("/cgi-bin/WebObjects/"+applicationName+".woa/wa/DirectAction/unfavoritePost","post="+encodeURIComponent(a),"unfavorite",processunfavorite)}
function processfavorite(){var a=requestObjects.favorite;if(4==a.readyState&&200==a.status)try{var b=eval("("+a.responseText+")"),c=b.postid,d=b.prompt,e=document.getElementById("faq"+c);e.style.visibility="inherit";e.innerHTML=d;e=document.getElementById("favoritePrompt"+c);e.innerHTML='<a href="#" onclick="unfavoritePost(\''+c+'\');return false;" title="Remove this post as a favorite">-</a>'}catch(f){alert("Sorry, there was a problem adding your favorite.")}}
function processunfavorite(){var a=requestObjects.unfavorite;if(4==a.readyState&&200==a.status)try{var b=eval("("+a.responseText+")"),c=b.postid,d=b.prompt,e=document.getElementById("faq"+c);e.style.visibility=0<d.length?"inherit":"hidden";e.innerHTML=d;e=document.getElementById("favoritePrompt"+c);e.innerHTML='<a href="#" onclick="favoritePost(\''+c+'\');return false;" title="Add this post as a favorite">+</a>'}catch(f){alert("Sorry, there was a problem removing your favorite.")}};requestObjects={};flagging=!1;function _sendRequest(a,b,c,d){var e;window.XMLHttpRequest?e=new XMLHttpRequest:window.ActiveXObject&&(isIE=!0,e=new ActiveXObject("Microsoft.XMLHTTP"));e&&(requestObjects[c]=e,e.onreadystatechange=d,e.open("POST",a,!0),e.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),e.setRequestHeader("charset","UTF-8"),a=b+"&wosid="+encodeURIComponent(sessionID)+"&woinst="+encodeURIComponent(instanceNumber)+"&x="+encodeURIComponent(sessionID),e.send(a))}
function _removeChildNodes(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
function showflags(a){if(!flagging){flagging=!0;var b=document.createElement("select");b.id="flagreason"+a;b.onchange=function(){flag(a)};for(var c=0;c<flagReasons.length;++c){var d=document.createElement("option");d.text=flagReasons[c].reason;d.value=flagReasons[c].id;b.options[b.length]=d}c=document.getElementById(a);c.appendChild(b);b=document.createElement("a");b.href="#";b.onclick=function(){cancelflag(a);return!1};b.target="_self";b.title="Cancel";b.innerHTML="<b>x</b>";c.appendChild(document.createTextNode(" ["));
c.appendChild(b);c.appendChild(document.createTextNode("]"))}return!1}function cancelflag(a){flagging=!1;_removeChildNodes(document.getElementById(a));return!1}function flag(a){var b=flagReasons[document.getElementById("flagreason"+a).selectedIndex].id;_sendRequest("/cgi-bin/WebObjects/"+applicationName+".woa/wa/DirectAction/flagPost","post="+encodeURIComponent(a)+"&reason="+encodeURIComponent(b),"flag",processflag)}
function faqflag(a){if(!confirm('The "FAQ" link alerts Paizo staff to posts which should be answered in the FAQ.\n\nAre you sure you want to flag this post?'))return!1;_sendRequest("/cgi-bin/WebObjects/"+applicationName+".woa/wa/DirectAction/faqPost","post="+encodeURIComponent(a),"faqflag",processfaqflag)}
function processflag(){var a=requestObjects.flag;if(4==a.readyState&&200==a.status)try{var b=eval("("+a.responseText+")").postid;document.getElementById("flagPrompt"+b).innerHTML='<span class="messageboardFlag">FLAGGED</span>';_removeChildNodes(document.getElementById(b));flagging=!1}catch(c){alert("Sorry, there was a problem adding your flag.")}}
function processfaqflag(){var a=requestObjects.faqflag;if(4==a.readyState&&200==a.status)try{var b=eval("("+a.responseText+")"),c=b.prompt,d=document.getElementById("faq"+b.postid);d.style.visibility="visible";d.innerHTML=c}catch(e){alert("Sorry, there was a problem adding your flag.")}};function toggleSpoiler(a){for(var b=a.nextSibling;b&&1!=b.nodeType;)b=b.nextSibling;b&&("block"!=b.style.display?(b.style.display="block",a.value="Hide"):(b.style.display="none",a.value="Show"))};